### ISSUE TITLE
operators dell-csi-operator: Some files are not updated for v1.7.0 as previous version (v1.6.0) is getting installed

### ISSUE THREAD

**Issue by rensyct** [k8s-operatorhub/community-operators#1006]
Latest version of dell-csi-operator is v1.7.0. PR for the same is **https://github.com/k8s-operatorhub/community-operators/pull/960** 
Followed the instructions to install dell-csi-operator on a K8s environment with OLM installed. 
But **kubectl create -f https://operatorhub.io/install/dell-csi-operator.yaml** installs the previous version (v1.6.0) of dell-csi-operator 

Expected behaviour - **kubectl create -f https://operatorhub.io/install/dell-csi-operator.yaml** should install the latest version of dell-csi-operator which is v1.7.0

**Comment by J0zi** [comment]
@rensyct it should be fixed now.

**Comment by rensyct** [comment]
It is fixed. Thank you @J0zi
