### ISSUE TITLE
clickhouse operator included in github, but missing on operatorhub.io

### ISSUE THREAD

**Issue by sunsingerus** [k8s-operatorhub/community-operators#102]
Hi there! Observe strange situation - how does it happen that clickhouse-operator it present in github repo [https://github.com/k8s-operatorhub/community-operators/tree/main/operators/clickhouse](https://github.com/k8s-operatorhub/community-operators/tree/main/operators/clickhouse) but is missing on [operatorhub](https://operatorhub.io/)?

**Comment by mvalarh** [comment]
I see that operator is there. https://operatorhub.io/operator/clickhouse

**Comment by mvalarh** [comment]
Closing. Please reopen when needed
