### ISSUE TITLE
YAML example for dell-csm-operator CRD is missing few fields. How can that be corrected

### ISSUE THREAD

**Issue by rensyct** [k8s-operatorhub/community-operators#1024]
### Discussed in https://github.com/k8s-operatorhub/community-operators/discussions/1008

<div type='discussions-op-text'>

<sup>Originally posted by **rensyct** March 31, 2022</sup>
YAML example for dell-csm-operator CRD was missing two fields. How can that be corrected? Samples are corrected and image is updated to have the correct entries. What step should be taken next so that OperatorHub will show the updated sample yaml files for the CRD</div>

I am converting this to an issue as I did not get any response in Q&A discussion thread. PR link - https://github.com/k8s-operatorhub/community-operators/pull/964

**Comment by mvalarh** [comment]
You can make pull request with operator version update. We allow to update in example field

**Comment by rensyct** [comment]
If there are only cosmetic changes in CSV, will I be able to modify the same operator version

**Comment by mvalarh** [comment]
Yes

**Comment by rensyct** [comment]
Hi @mvalarh , Please help merge this PR https://github.com/k8s-operatorhub/community-operators/pull/1036. This has few changes in the CSV only

**Comment by rensyct** [comment]
@mvalarh , @J0zi 
I have updated the CSV of dell-csm-operator for few cosmetic changes. Please help merge the PR (https://github.com/k8s-operatorhub/community-operators/pull/1036) 
Original PR which is merged - https://github.com/k8s-operatorhub/community-operators/pull/964

**Comment by rensyct** [comment]
PR is merged and the updated CSV is reflected now
