### ISSUE TITLE
CI KIWI test is now using kube 1.21, not 1.22

### ISSUE THREAD

**Issue by houshengbo** [k8s-operatorhub/community-operators#1163]
There is a revert of the kube version of he kiwi ci test.
It was using 1.21, but later changed to use 1.22, so knative operator can pass.
But now it is back to use kube 1.21.

@mvalarh

**Comment by mvalarh** [comment]
Yes, we had to revert. We are currently designing how we are going to handle such situation. Temporary i can enable it for you if needed.

**Comment by houshengbo** [comment]
Right. It will be great, if you can make knative-operator an exception to run on kube 1.22.

**Comment by camilamacedo86** [comment]
HI @J0zi @mvalarh, 

The latest Kind version uses 1.23. Could we not update it?

**Comment by fbladilo** [comment]
@camilamacedo86 @mvalarh Same is happening to us with Kiwi tests #1310 (Tackle beta.1 requires v1.22 minKubeVersion) and we are set to release on Jun 16th our stable, will probably run into it again, are exceptions possible per project?

**Comment by mvalarh** [comment]
We are working on dynamic k8s version. We will use latest k8s and if `operatorhub.io/ui-metadata-max-k8s-version: "1.21"` is specified we will use ks8 `1.21`. This feature should be ready this week.

**Comment by mvalarh** [comment]
This is in production thanks to @J0zi
