### ISSUE TITLE
Error: error loading bundle into db: FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by yossig-aquasec** [k8s-operatorhub/community-operators#1195]
Hi we are getting failure with the following pr #1193 testing: https://github.com/k8s-operatorhub/community-operators/runs/6351359872?check_suite_focus=true
can you please advice us what is the cause for this issue?
is it because we are using packagemanifest instead of bundle in the packaging format?
We update the following annotation: olm.maxOpenShiftVersion",from 3.9 to  4.10

**Comment by J0zi** [comment]
this line https://github.com/k8s-operatorhub/community-operators/runs/6351359872?check_suite_focus=true#step:3:7241
@camilamacedo86 does it look like `opm` issue?

**Comment by yossig-aquasec** [comment]
we are also failing in here:
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1181

**Comment by camilamacedo86** [comment]
@J0zi, 

Regards the comment:


> this line https://github.com/k8s-operatorhub/community-operators/runs/6351359872? check_suite_focus=true#step:3:7241
> @camilamacedo86 does it look like opm issue?


The error is: 

```
    time="2022-05-10T08:01:09Z" level=error msg="permissive mode disabled" bundles="[quay.io/openshift-community-operators/aqua:v6.5.0 quay.io/openshift-community-operators/aqua:v6.5.1 quay.io/openshift-community-operators/aqua:v6.5.2 quay.io/openshift-community-operators/aqua:v6.5.3 quay.io/openshift-community-operators/aqua:v6.5.4 kind-registry:5000/test-operator/aqua:v6.5.5]" error="unable to determine default channel among channel heads: map[6.5.0:{name:aqua-operator.v6.5.5 version:{Major:6 Minor:5 Patch:5 Pre:[] Build:[]} count:1}]"
    Error: unable to determine default channel among channel heads: map[6.5.0:{name:aqua-operator.v6.5.5 version:{Major:6 Minor:5 Patch:5 Pre:[] Build:[]} count:1}]
    Usage:
      opm index add [flags]
```

```
TASK [test_operator_update : Update status if wrong] ***************************
fatal: [localhost]: FAILED! => changed=false 
  msg: 'Operator upgrade failed, you can debug locally by 2 commands: ''operator sdk run bundle BUNDLE_N-1; operator-sdk run bundle-upgrade BUNDLE_N''  [FAIL]' 
```
The error seems to be in the run bundle upgrade and OPM was unable to add the bundle `unable to determine default channel among channel heads: map[6.5.0:{name:aqua-operator.v6.5.5 version:{Major:6 Minor:5 Patch:5 Pre:[] Build:[]} count:1}]`

Note that OLM follows semver and bundles as the operators also should follow; https://semver.org/
Then, the error here shows to be because we are trying to add bundle version > then the head of the channel. 
Also, it might be related to the default channel configuration. 

However, for we are able to check this one following are some questions:

a) Why do we call `operator-sdk run bundle-upgrade BUNDLE_N` in the pipeline? When it is required?
b) What is the SDK version used? By knowing that, we can check what is the OPM version used, see: https://github.com/operator-framework/operator-sdk/blob/master/go.mod#L21 

About the PR: 

a) Why they are setting max OCP version = 10 and keeping the message about adding automatically for 4.9? 
See: https://github.com/k8s-operatorhub/community-operators/blob/cb34107e183886ae19913d79bf4d7113033af36e/operators/aqua/6.5.5/aqua-operator.v6.5.5.clusterserviceversion.yaml#L7-L14. @yossig-aquasec could you please clarify your motivation with?

**Comment by yossig-aquasec** [comment]
@camilamacedo86 thanks, I forgot to update the 4.9 to 4.10 in the description, but if the cause is because the default channel we will try to update to bundle format (i also need to update it in the prod ).
But if we need to update it to bundle, are we need to update all folders or just the new ver?

**Comment by camilamacedo86** [comment]
@yossig-aquasec, why are you using the property `olm.maxOpenShiftVersion` version to publish a solution in the OperatorHub? Also, why a solution that works on 4.9 would not work on 4.10 OCP? Could you please check my comment: https://github.com/k8s-operatorhub/community-operators/pull/1193#discussion_r869035791

**Comment by yossig-aquasec** [comment]
We are allowing new ocp  versions only after we are certified it with our dev

**Comment by camilamacedo86** [comment]
@yossig-aquasec, @J0zi 

Regards distributions using `olm.maxOpenShiftVersion`:
a) it is required check why they are using it here and what is the intention
b) the config used in the CSV does not seems accurate
c) it shows that we misunderstand when/why to use it as its purpose. 

Regards the issue faced when:

> @camilamacedo86, we are testing if operator can upgrade from quay.io/operatorhubio/aqua:v6.5.4 to kind-registry:5000/test-operator/aqua:v6.5.5.
- operator-sdk v1.18.1 were using another version : https://github.com/operator-framework/operator-sdk/blob/v1.18.1/go.mod#L20

What was the SDK version used before?
Could we try to test manually if the issue can be reproduced with SDK 1.19.1? 
Then, can we check if the issue does not occur with the previous version used? 

If that is the case, then we need to see if we have a bug or sdk/opm was changed or fixed, and now we are checking error. However, the first step seems to see if we can reproduce the scenario with previous versions.

**Comment by camilamacedo86** [comment]
Hi @J0zi, 

Also, what the field `packagemanifestClusterVersionLabel ` in does: https://github.com/k8s-operatorhub/community-operators/blob/main/operators/aqua/ci.yaml#L9

**Comment by camilamacedo86** [comment]
Hi @J0zi,

I tried to check this one further:

The error ` error loading bundle into db: FOREIGN KEY constraint failed` came from: https://github.com/operator-framework/operator-registry/blob/master/pkg/sqlite/directory.go#L174. So the error came from [here](https://github.com/operator-framework/operator-registry/blob/aa8db09278a0ea30dd7cf07e3b197a3d7b5ce034/pkg/sqlite/load.go#L550-L745).

I did not find any recent change in SDK or OPM in this area that could introduce a new bug. _(so I do not think that is too much valid to spend effort trying to test it with old versions)_

Also, by checking the logs to see where it fails in the SDK command ([here](https://github.com/operator-framework/operator-sdk/blob/master/internal/olm/operator/registry/operator_installer.go#L102) is the code), see: https://github.com/k8s-operatorhub/community-operators/runs/6352972137?check_suite_focus=true#step:3:5619

In this way, I think we can: 

a) Reproduce the issue locally, how:

See that the error came here:

```
    - 'Error: error loading bundle into db: FOREIGN KEY constraint failed'
    - 'Usage:'
    - '  opm registry add [flags]'
```

So, if we covert the package manifest to bundle and try to add in the operatorhub index with `opm registry add,` are we able to check this issue or not? If yes, great we have all that is required to raise an issue to OPM and ask for help here. 

If not, are we able to reproduce locally is operator-sdk run bundle at least?

**Comment by camilamacedo86** [comment]
We could find a way to reproduce the issue with OPM and without SDK. So, we raise an issue for we get it fixed in OPM: https://github.com/operator-framework/operator-registry/issues/952

**Comment by mvalarh** [comment]
Closing, because aqua operator is in bundle format and it is merged. Reopen when needed

**Comment by yossig-aquasec** [comment]
@mvalarh our pr wasn't merged yet, can you check it please?

**Comment by camilamacedo86** [comment]
Also, would be nice if we could have here:
a) One PR to migrate all distributions to the bundle format ( without add a new one )
b) after the above PR push a PR to add a new bundle: Why? the checks will not be done if we add all in the same PR and we will not able to see if the new distribution has others errors or if migrating the solution to bundle format for example sorted out this scenario.

@yossig-aquasec wdyt? Could we try to do that? 

c/c @mvalarh @J0zi

**Comment by yossig-aquasec** [comment]
@camilamacedo86  no problem, I will remove the new ones and rebase + push

**Comment by yossig-aquasec** [comment]
done

**Comment by camilamacedo86** [comment]
@yossig-aquasec regards the PR: https://github.com/k8s-operatorhub/community-operators/pull/1193

See that you are removing the annotation added in all distributions that cannot work on 1.22 because is possible to check that API versions were removed on 1.22. This annotation informs its users that they cannot use these versions on 1.22+. Why are you removing them?

Could you revert it?

**Comment by yossig-aquasec** [comment]
same issue with the following:
https://github.com/k8s-operatorhub/community-operators/pull/1222

**Comment by camilamacedo86** [comment]
Hi @yossig-aquasec, 

In this PR, you are adding two bundles.
Could you please create one PR for each distribution?

**Comment by mvalarh** [comment]
Is it ok to close this one?

**Comment by yossig-aquasec** [comment]
Hi, yes. Thanks

**Comment by camilamacedo86** [comment]
@J0zi @mvalarh the scenario faced here is tracked in : https://github.com/operator-framework/operator-sdk/issues/5773
