### ISSUE TITLE
operator release pipeline is failing at OHIO stage

### ISSUE THREAD

**Issue by yossig-aquasec** [k8s-operatorhub/community-operators#1327]
https://github.com/k8s-operatorhub/community-operators/actions/runs/2494848835

**Comment by mvalarh** [comment]
@yossig-aquasec i happens from time to time. This part is fixed when next PR is merged. Or we are restarting it by hand. I think we can improve retry for this case. Thanks for reporting

**Comment by mvalarh** [comment]
Retry is implemented
