### ISSUE TITLE
Percona Postgres operator install mode

### ISSUE THREAD

**Issue by blezoray** [k8s-operatorhub/community-operators#1343]
Hello,

in the clusterserviceversion file of the Percona Postgres Operator, the supported installMode is only OwnNamespace : 
https://github.com/k8s-operatorhub/community-operators/blob/main/operators/percona-postgresql-operator/1.2.0/percona-postgresql-operator.v1.2.0.clusterserviceversion.yaml#L224

But, in the Percona Repo, it supports other modes:
https://github.com/percona/percona-postgresql-operator/blob/main/installers/olm/postgresoperator.csv.yaml#L59

Is it possible to allow all supported modes ?

Rgds.

**Comment by J0zi** [comment]
@cap1984 FYI

**Comment by cap1984** [comment]
Hi

We've decided to narrow the scope of possible namespace deployment options just for keeping our users safe. 
Thus there is no plans to change such a behavior in the future.
