### ISSUE TITLE
PR title expects "operators" instead of "operator"

### ISSUE THREAD

**Issue by dcurran90** [k8s-operatorhub/community-operators#1362]
This repo expects the PR titles to start with "operators" instead of "operator". This makes it inconsistent with other repositories such as https://github.com/redhat-openshift-ecosystem/certified-operators. 
The term "operator" seems to be a more accurate and would provide some convenience when submitting.

**Comment by mvalarh** [comment]
In our case it is directory, but sure we can change it

**Comment by mvalarh** [comment]
It is fixed now.
