### ISSUE TITLE
Skipping e2e for tektoncd-operator (0.60.0)

### ISSUE THREAD

**Issue by sm43** [k8s-operatorhub/community-operators#1435]
I was trying to release latest version for tektoncd-operator for operator hub but am not able to pass the CI.  
Pull req : https://github.com/k8s-operatorhub/community-operators/pull/1424

with `tektoncd-operator`, we package multiple CRDs, one of which is `TektonInstallerSet`
when operator is installed, it internally creates an instance of `TektonInstallerSet` for some internal resources.

now in CI, after installation, it removes deployments and then CRDs
while removing `TektonInstallerSet` CRD it gets blocked as instance is already on cluster with finalizer set
and as deployments are already deleted, it will blocks indefinitely
so the deletion of CRD is getting timeout

is there any way I can override CI script or skip the e2e in this case?
or any other suggestion?

**Comment by sm43** [comment]
cc @J0zi @mvalarh

**Comment by mvalarh** [comment]
How can we detect such case?

**Comment by sm43** [comment]
> How can we detect such case?

so this happens while uninstallation of operator too, if we uninstall deployments get removed but CRD instances will not be deleted as finalizers is set and controllers are not there to remove them.
so we recommended users to delete all CR instances and then uninstall.

in CI can we delete the CRDs first and then rest of the resources?

**Comment by J0zi** [comment]
@sm43 fixed, we are able to remove resources smoothly. Thank you for raising this issue.
