### ISSUE TITLE
Support for persistent volume mounted to Operator

### ISSUE THREAD

**Issue by vivekr-splunk** [k8s-operatorhub/community-operators#1555]
Hello, We are working on splunk operator. version 2.0.0 of splunk operator requires persistent volume to be mounted to splunk operator deployment. but bundle creation using olm do not allow persistent volume creation. How can I support in bundle certification for community operator to create persistent volume when I create PR for running any actions.

**Comment by dmesser** [comment]
@vivekr-splunk currently this is not possible to be bundle within the OLM package spec. We are however working on this for a newer version of OLM, see here: https://github.com/operator-framework/rukpak

In the meantime you could try to create the PVC at startup of your operator but it will require your controller to have those permissions which is against least privilege principle.

Out of curiosity: why does your controller need a PVC?
