### ISSUE TITLE
Create custom catalogs using this repo

### ISSUE THREAD

**Issue by rohasharma** [k8s-operatorhub/community-operators#1972]
Hi,

I want to create a custom catalogs with only few of the operators listed under operators dir. (Only 4 of them)
I am following a blog post (https://techbloc.net/archives/4372) which is mentions of building a new image from the Dockerfile present and then use the image created for my CatalogSource. 
Followed the same steps however, my custom catalog pod is throwing the below error:
`Error: open /etc/nsswitch.conf: permission denied
Usage:
   [flags]

Flags:
  -d, --database string          relative path to sqlite db (default "bundles.db")
  -h, --help                     help for this command
  -p, --port string              port number to serve on (default "50051")
      --skip-migrate             do  not attempt to migrate to the latest db revision when starting
  -t, --termination-log string   path to a container termination log file (default "/dev/termination-log")

time="2022-11-23T06:23:46Z" level=panic msg="open /etc/nsswitch.conf: permission denied"
panic: (*logrus.Entry) (0x1132a20,0xc0001bbb20)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000ba000, 0xc0001ff800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/vendor/github.com/sirupsen/logrus/entry.go:239 +0x2db
github.com/sirupsen/logrus.(*Entry).Log(0xc0001bbab0, 0xc000000000, 0xc00014df40, 0x1, 0x1)
	/build/vendor/github.com/sirupsen/logrus/entry.go:268 +0xeb
github.com/sirupsen/logrus.(*Logger).Log(0xc0000ba000, 0x0, 0xc00014df40, 0x1, 0x1)
	/build/vendor/github.com/sirupsen/logrus/logger.go:192 +0x7d
github.com/sirupsen/logrus.(*Logger).Panic(...)
	/build/vendor/github.com/sirupsen/logrus/logger.go:233
github.com/sirupsen/logrus.Panic(...)
	/build/vendor/github.com/sirupsen/logrus/exported.go:129
main.main()
	/build/cmd/registry-server/main.go:51 +0xbe`
	
Can someone please help me out here?

**Comment by J0zi** [comment]
@rohasharma despite your question is out of our scope, I would suggest creating an index in file based catalog (FBC) format. Something like
```
opm migrate quay.io/operatorhubio/catalog:latest <output_dir> --output=yaml
```
delete unwanted operators from `output_dir`
```
opm generate dockerfile <config_path>
```
build it
