### ISSUE TITLE
docker build of upstream.Dockerfile fails

### ISSUE THREAD

**Issue by akihikokuroda** [k8s-operatorhub/community-operators#241]
docker image build with upstream.Dockerfile fails at https://github.com/k8s-operatorhub/community-operators/blob/03e9cad590cd15922aa4ed2a9a1c2d250741dbec/upstream.Dockerfile#L3

Should it be just `COPY operators manifests` instead of `COPY upstream-community-operators manifests` ?

**Comment by mvalarh** [comment]
Where are you using it? We just have it there to generate info in operatorhub.io web page
