### ISSUE TITLE
Multiarch support

### ISSUE THREAD

**Issue by sxd** [k8s-operatorhub/community-operators#262]
Hi,

We been adding multi-arch support to our cloud-native-postgresql operator in the past few days but we hit a few bugs that were fixed on https://github.com/operator-framework/operator-registry but in community-operators the catalog is created using the old image `upstream-registry-builder` which is reported as deprecated since it use deprecated apps https://github.com/operator-framework/operator-registry/issues/805

Possible solution, is it possible to switch and use the latest operator-registry/opm image? We can propose a PR but we don't really know if the community-operators wants to update that. 

Our understanding is that we just need to update this Dockerfile https://github.com/k8s-operatorhub/community-operators/blob/main/upstream.Dockerfile if that's right we can propose an update.

Best Regards,

**Comment by sxd** [comment]
@dmesser We know that probably is not the solely change but we need to start at some point and start doing some PRs from there, and basically we need to start by knowing where the image is built and start to do some work on it, otherwise we cannot help, and as you can see there's already people knowing about this and deprecate the use of the old image is important since it can be discarded in the near future.

**Comment by sxd** [comment]
So for your information the ticket on `operator-framework/operator-registry` https://github.com/operator-framework/operator-registry/issues/805 has been closed expecting to the community-operator switch images

**Comment by ionutz89** [comment]
Any update about it?

**Comment by J0zi** [comment]
@ionutz89 @sxd good news! Priorities have changed and we are going to deliver multiarch k8s index.

**Comment by mvalarh** [comment]
@sxd we are producing multiarch index image now. Can you please check if ok with you? If ok please close issue. Thanks
