### ISSUE TITLE
Build failure: OHIO image / k8s

### ISSUE THREAD

**Issue by wallrj** [k8s-operatorhub/community-operators#2936]
My recent cert-manager operator releases have not appeared on operatorhub.io, probably due to a CI failure:
 * https://github.com/k8s-operatorhub/community-operators/actions?query=branch%3Amain+is%3Afailure

xref:
*  https://github.com/k8s-operatorhub/operatorhub.io/issues/55

**Comment by qbarrand** [comment]
Also seen on the commit for #2907: [failed job](https://github.com/k8s-operatorhub/community-operators/actions/runs/5347840881/jobs/9697397023)

**Comment by mporrato** [comment]
This has been fixed and the index is now up to date.
