### ISSUE TITLE
etcd operator Install fails on k8s 1.22 - use of depcrecated api apiextensions.k8s.io/v1beta1 no longer served

### ISSUE THREAD

**Issue by markleeibm** [k8s-operatorhub/community-operators#323]
The apiextensions.k8s.io/v1beta1 API version of CustomResourceDefinition is no longer served as of k8s v1.22.

    Migrate manifests and API clients to use the apiextensions.k8s.io/v1 API version, available since v1.16.
    All existing persisted objects are accessible via the new API
   
see: https://kubernetes.io/docs/reference/using-api/deprecation-guide/

The olm subscription indicates the failure with the following

   lastUpdated: "2021-10-20T19:26:20Z"
    conditions:
    - lastTransitionTime: "2021-10-20T19:26:20Z"
      message: all available catalogsources are healthy
      reason: AllCatalogSourcesHealthy
      status: "False"
      type: CatalogSourcesUnhealthy
    - status: "False"
      type: ResolutionFailed
    - lastTransitionTime: "2021-10-20T19:44:42Z"
      message: 'api-server resource not found installing CustomResourceDefinition
        etcdbackups.etcd.database.coreos.com: GroupVersionKind apiextensions.k8s.io/v1beta1,
        Kind=CustomResourceDefinition not found on the cluster. This API may have
        been deprecated and removed, see https://kubernetes.io/docs/reference/using-api/deprecation-guide/
        for more information.'

message: 'api-server resource not found installing CustomResourceDefinition
        etcdbackups.etcd.database.coreos.com: GroupVersionKind apiextensions.k8s.io/v1beta1,
        Kind=CustomResourceDefinition not found on the cluster. This API may have
        been deprecated and removed, see https://kubernetes.io/docs/reference/using-api/deprecation-guide/
        for more information.'

**Comment by camilamacedo86** [comment]
Hi @markleeibm, 

Are you looking here for the operator to be upgraded? If yes, then you need to open this issue in the maintainer repository. Could you please raise this issue in the project repo?

**Comment by camilamacedo86** [comment]
@mvalarh @J0zi 
I think we can close this one.
