### ISSUE TITLE
OperatorHub doc update

### ISSUE THREAD

**Issue by sabinaaledort** [k8s-operatorhub/community-operators#36]
Hi, 

I think the [How to contribute an Operator doc](https://operatorhub.io/contribute) should be updated due to [this](https://github.com/operator-framework/community-operators/issues/4159) repos change. The doc it pointing to the old repo.

**Comment by mvalarh** [comment]
We are working on it

**Comment by mvalarh** [comment]
It will be fixed when https://github.com/k8s-operatorhub/operatorhub.io/pull/3 will be merged

**Comment by mvalarh** [comment]
Merged. Feel free to reopen when needed
