### ISSUE TITLE
Suggestion to change stale bot configuration 

### ISSUE THREAD

**Issue by Noah-Huppert** [k8s-operatorhub/community-operators#3641]
Hi,

I had [an issue](https://github.com/k8s-operatorhub/community-operators/issues/3254) which I submitted. After not receiving a response from maintainers for 1 month the bot closed the issue.

I am completely sympathetic to the limited time of maintainers, and different expectations for how much support they want to offer. I also think even if there is no involvement from maintainers keeping an issue open helps boost visibility of the issue, and allows the community to discuss solutions and workarounds. Best case a community member might even put in a PR for an open issue.

If possible I'd hope to suggest either removing the stale bot or changing it so it only marks issues as stale if a maintainer is waiting for information from a reporter.

**Comment by 0xErnie** [comment]
You could create a PR for _.github/workflows/stale_issues.yaml_ with a configuration you would prefer. Pull Requests are not marked stale ;)
