### ISSUE TITLE
Location of community-operators index image is not documented

### ISSUE THREAD

**Issue by adambkaplan** [k8s-operatorhub/community-operators#382]
On operatorhub.io, the location of the community-operators index image is not documented anywhere. This makes it challenging for operator authors to test their bundles if their ClusterServiceVersion depends on other APIs, and therefore the test catalog needs to contain an operator bundle which provides the referenced APIs.

Please provide the location of where the index image is published, and/or the locations of the bundle images build from this repository.

**Comment by awgreene** [comment]
Hello @adambkaplan,

The Upstream Community operator image can be found [here](https://github.com/operator-framework/operator-lifecycle-manager/blob/58c8485b2ac3001b9b44fabb9369bae5362087d4/deploy/upstream/quickstart/olm.yaml#L341), the image is `quay.io/operatorhubio/catalog:latest`.

I agree that this should be made more visible.

**Comment by camilamacedo86** [comment]
Created a PR to address this need see: #452
