### ISSUE TITLE
Upbound Universal Crossplane (UXP) is very out of date

### ISSUE THREAD

**Issue by deleocj** [k8s-operatorhub/community-operators#4201]
Current version on operator hub: 1.5.1-up.1
Latest version of Upbound Universal Crossplane (UXP): [1.15.2-up.1](https://github.com/upbound/universal-crossplane/releases/tag/v1.15.2-up.1)

**Comment by mporrato** [comment]
@muvaf @negz @hasheddan @turkenh @AaronME FYI

**Comment by deleocj** [comment]
Any update on getting the version increased?
