### ISSUE TITLE
Bundle merged cannot be load by the operator-framework/api

### ISSUE THREAD

**Issue by camilamacedo86** [k8s-operatorhub/community-operators#435]
**Description**
The following distribution cannot be load via operator-framework/api
https://github.com/k8s-operatorhub/community-operators/blob/main/operators/litmuschaos/1.9.0/

Error: `unable to parse CRD chaosengines.litmuschaos.io.crd.yaml: error converting YAML to JSON: yaml: line 81: could not find expected ':',`

This issue is probably raised when we try to migrate the package manifest to bundle. Then, it shows for me that we need:

a) Contact the author to fix the manifest 
b) Ensure that in the ci/pipeline we: 

- Ensure that we raise errors if we are unable to convert the pkg to bundle 
- Check if we are calling in the CI/Pipeline `operator-sdk bundle validate ./bundle --select-optional name=operatorhub` to ensure the distributions.

**Comment by camilamacedo86** [comment]
c/c @mvalarh @J0zi

**Comment by camilamacedo86** [comment]
Hi @J0zi,

Thank you for check that the ci/pipeline is all fine and doing the check : https://github.com/k8s-operatorhub/community-operators/runs/4352474905?check_suite_focus=true#step:6:975

So, we just need to contact the author to let them know they need to fix its manifest.

**Comment by J0zi** [comment]
> Hi @J0zi,
> 
> Thank you for check that the ci/pipeline is all fine and doing the check : https://github.com/k8s-operatorhub/community-operators/runs/4352474905?check_suite_focus=true#step:6:975
> 
> So, we just need to contact the author to let them know they need to fix its manifest.

this was intentional test from `do-not-merge` branch, should fail, works as designed

**Comment by J0zi** [comment]
succesfully subscribed to production

```
default                                            chaos-operator-54c5dd5d5f-m8whh                                   1/1     Running     0          47s
➜  ~ 

```
![image](https://user-images.githubusercontent.com/51358681/145963981-9e1777d4-8e9c-4ddf-a626-db0c3e37b036.png)
