### ISSUE TITLE
Would like to change the name of a category, what is the process for that?

### ISSUE THREAD

**Issue by eriknelson** [k8s-operatorhub/community-operators#475]
Hello, we'd like to update a name of a migration category from "Modernization & Migration" to "Migration and Modernization". Could someone help me understand what the process for that change would be, and what kind of approvals are necessary in order to apply that change?

Somehow these community operator categories are also shared by downstream OpenShift operators, see screenshot:

![image](https://user-images.githubusercontent.com/410933/144900782-05cbcb39-5449-4924-ab46-2d8e2800f201.png)

If a downstream operator specifies a Category that is also shared by the Categories specified here, will OLM simply merge them into the same category? Who are the right people to reach out to to ask these questions? I'm also available at ernelson <at> redhat <dot> com since this issue seems to straddle both upstream operatorhub and downstream.

**Comment by eriknelson** [comment]
Any updates on this?

**Comment by camilamacedo86** [comment]
Hi @eriknelson, 

You can only use these categories: https://github.com/operator-framework/api/blob/master/pkg/validation/internal/operatorhub.go#L143-L159

To publish your project need to pass in the validator: https://github.com/operator-framework/api/blob/master/pkg/validation/internal/operatorhub.go#L21-L125

You can test locally your bundle with [Operator-SDK](https://github.com/operator-framework/operator-sdk) `operator-sdk bundle validate ./bundle --select-optional suite=operatorframework` 

These categories/checks are also used/required to publish in OCP as you checked out. 
So, I do not think that we can change the order of the name without causing a significant.

I hope that it helps you out. Also, please feel free to ping me on the slack(cmacedo) if you need more info and help.

**Comment by camilamacedo86** [comment]
Closing this one as sorted out based on the comment: https://github.com/k8s-operatorhub/community-operators/issues/475#issuecomment-1006981654

However, please feel free to re-open this one or raise new issues if you see that fits.
