### ISSUE TITLE
Build failure: OHIO image / k8s

### ISSUE THREAD

**Issue by wallrj** [k8s-operatorhub/community-operators#4767]
@mporrato @Allda I think the release process failed:
 * https://github.com/k8s-operatorhub/community-operators/actions/runs/10165227653

Can you help?

ArtifactHub has the latest release:
 * https://artifacthub.io/packages/olm/community-operators/cert-manager/1.15.2

But the operatorhub.io page is currently out of date:
![image](https://github.com/user-attachments/assets/a16521ae-bbe1-4afc-9c7b-bed48c44f886)

_Originally posted by @wallrj in https://github.com/k8s-operatorhub/community-operators/issues/4761#issuecomment-2258720506_

Previous example of this failure:
 * https://github.com/k8s-operatorhub/community-operators/issues/2936

**Comment by cheels** [comment]
@wallrj Thanks for rising the issue. 
We also encountered the same issue with our 5.13.0 Operator. The PR #4757 was merged, and the workflow passed, but the publishing step was skipped: https://github.com/k8s-operatorhub/community-operators/actions/runs/10148514691.

Now the latest version should be 5.13.0 not 5.12.0
<img width="1498" alt="image" src="https://github.com/user-attachments/assets/412b105d-aada-46ab-b8ba-6789ad16fd1b">

**Comment by wallrj** [comment]
We spotted "no space left on device" in the build logs and assume that's the problem:
> 2024-07-30T16:04:33.6441357Z [0;31m    Error: identifier is not a container: preparing container for next step: creating build container: creating container: creating read-write layer with ID "85dc1973cac2431be1ff2073956c0184e619726864143500462ee72a75b5389f": **no space left on device**[0m

**Comment by Allda** [comment]
The issue with no space left on a device has been fixed recently and all previously failed releases should be fixed now. Can you please check again and confirm everything is ok now?

**Comment by wallrj** [comment]
> The issue with no space left on a device has been fixed recently and all previously failed releases should be fixed now. Can you please check again and confirm everything is ok now?

Yes, cert-manager v1.15.2 is now appearing: https://operatorhub.io/operator/cert-manager/stable/cert-manager.v1.15.2
