### ISSUE TITLE
PR is not getting merged automatically even when bot added /merge-possible label

### ISSUE THREAD

**Issue by rajendraindukuri** [k8s-operatorhub/community-operators#5129]
Hi,

As part of the certification process, we raised a PR  https://github.com/k8s-operatorhub/community-operators/pull/5107

Even though the pipeline checks are passing and /merge-possible label is added by bot, PR is not getting merged

Can you please help with closing this PR?

Thanks

**Comment by mporrato** [comment]
That's the expected behaviour. If you want to have the PRs auto merged, you need to provide a list of authorised reviewers in your ci.yaml file. Once the the PR has been approved by a reviewer then you can get it merged by issuing `/hold` and '/hold cancel`.
In the meantime, I've merged #5107.
