### ISSUE TITLE
Operator test / PR-traffic-light PR check is failing 

### ISSUE THREAD

**Issue by shefali-malhotra** [k8s-operatorhub/community-operators#5296]
Seeing the operator PR traffiv light check for the following PR  https://github.com/k8s-operatorhub/community-operators/pull/5291
Any leads in the fixing that.

**Comment by shefali-malhotra** [comment]
@mporrato Could you please help look into this .

**Comment by mporrato** [comment]
@shefali-malhotra your csv is malformed:

```
$ operator-sdk bundle validate 1.7.0
FATA[0000] unable to find a csv in bundle directory 1.7.0/manifests 
$ find 1.7.0
1.7.0
1.7.0/manifests
1.7.0/manifests/containerstoragemodules.storage.dell.com.crd.yaml
1.7.0/manifests/dell-csm-operator.v1.7.0.clusterserviceversion.yaml
1.7.0/metadata
1.7.0/metadata/annotations.yaml
1.7.0/tests
1.7.0/tests/scorecard
1.7.0/tests/scorecard/config.yaml
$ yamllint -c <(printf "rules:\n  line-length: disable\n") 1.7.0/
1.7.0/manifests/dell-csm-operator.v1.7.0.clusterserviceversion.yaml
  4447:5    error    syntax error: expected <block end>, but found '?' (syntax)
```

**Comment by shefali-malhotra** [comment]
Thanks @mporrato for pointing out the CSV issue. After fixing all the formatting issue now the operator upgrade and olm install tests are failing in PR. 
From the logs it looks operator controller pod is going in ImagePullBackoff error but exactly which image it is unable to pull could you please provide those details if possible. Similar error is being observed with olm install.

**Comment by shefali-malhotra** [comment]
@mporrato thanks for pointing the issue. Is there any alternative to use the redHat packaged images as our customers are expecting to use the same. 
Also, for community and certified operator the pipeline tests were passed with the same image and PRs are merged.
We have also checked that if same image is available as part of other redHat registries that do not need authentication, but this image is only available on registry.redhat.io which requires authentication.

**Comment by mporrato** [comment]
@shefali-malhotra your requirement is not compatible with this repository: the operators in this repo are supposed to be installable on any kubernetes cluster, not just openshift clusters.

**Comment by shefali-malhotra** [comment]
@mporrato thanks for providing the details. We internally had discussion how to handle this scenario from customer perspective.  and for this release have reverted that image to point to one present on docker hub. Please review the PR.

**Comment by shefali-malhotra** [comment]
closing the issue as PR is merged.
