### ISSUE TITLE
Alphabetical sorting on operatorhub.io is putting deprecated operators first

### ISSUE THREAD

**Issue by TBBle** [k8s-operatorhub/community-operators#549]
Looking at [operatorhub.io](https://operatorhub.io/), the top looks like this:

![image](https://user-images.githubusercontent.com/138397/148350284-a452184e-f691-4dd3-942c-91d941eecbe1.png)

_My first-blush reaction was that operatorhub.io itself had been deprecated, which is an unfair reaction driven by my having lived through the github.com/helm/charts deprecation..._

Anyway, I assume the underlying cause is that alphabetically, `[` sorts before `A`, and there's no rule preventing naming your operator to (intentionally or unintentionally) take advantage of that.

Putting `[Deprecated]` at the start of the name of a deprecated operator's entry isn't ideal, but there isn't a "deprecated" field or similar in [`ClusterServiceVersion` v1alpha1](https://docs.openshift.com/container-platform/4.9/rest_api/operatorhub_apis/clusterserviceversion-operators-coreos-com-v1alpha1.html) that could be used specifically for this.

Perhaps recognising a `deprecated` value for the `maturity` free-string field would work? Or perhaps this is something that should be at the channel level instead, to deprecate a whole operator, rather than a specific version?

Anyway, with that metadata being distinguished, then deprecated operators could be hidden by default, and searched as a separate axis, and the deprecation status could be made visible via something other than the name field.

**Comment by wallrj** [comment]
I took the liberty of duplicating your issue in the operatorhub.io repo because it was bugging me too.
I added some extra information about the `maturity: deprecated` thing.

**Comment by camilamacedo86** [comment]
Hi @wallrj, 

Thank you for letting us know that you are also looking for this feature. 
IHMO: Using the maturity field does not seem fit. 

The CSV is specific per bundle. For this scenario, shows that we would need to have a way to let the authors define what are the packages which will be discontinued and at some point removed from the index catalog ( operatorhub ). 

We might no longer have CSV manifests in the future, see: https://github.com/operator-framework/enhancements/blob/master/enhancements/csvless-bundles.md

Then, it seems that we could use the [OLM properties](https://olm.operatorframework.io/docs/concepts/olm-architecture/dependency-resolution/#arbitrary-properties) to define it, something like: 

```
properties:
- type: olm.package_discontinued
  value:
    message: "This package is discontinued and is planned to be removed at DD/MM/YYYY. Please, ensure that you use its Backup Service in favor to move forward and began to use the project MyOperator. For further information see: <link>."
```

However, it shows also a reasonable request for all other catalogues such as https://github.com/redhat-openshift-ecosystem/community-operators-prod. 

c/c @mvalarh @J0zi @dmesser

**Comment by camilamacedo86** [comment]
The option to add a feature to address this requirement has been discussed into the EP: https://github.com/operator-framework/enhancements/pull/113/files
