### ISSUE TITLE
Couchdb operator issue: not saving settings

### ISSUE THREAD

**Issue by rreyesg28** [k8s-operatorhub/community-operators#601]
I have couchdb installed on an eks cluster, I have a problem every time the POD is restarted or deleted, the configuration is lost.
So far I haven't found any solution that saves the configuration even when the cluster is restarted.
The only thing that comes close to a solution is to add referenced fields to the configuration, however this option does not allow adding all the fields of the configuration.

[https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-configure-couchdb-cluster](url)

**Comment by camilamacedo86** [comment]
Hi @rreyesg28, 

It is an issue/bug with the project / Operator itself. This repo is only to allow the Operator Authors to distribute their solutions in the https://operatorhub.io/ and in its OLM index catalog (. quay.io/operatorhubio/catalog:latest ). 

So, you need to reach out to the Operator authors/maintainers. Could you please raise this issue in their repo? 

In this way, I am closing. this one.
