### ISSUE TITLE
prometheus operator is out of date 0.47.0 vs 0.54.0

### ISSUE THREAD

**Issue by paulczar** [k8s-operatorhub/community-operators#708]
The upstream prometheus operator is many releases ahead of the what is available in operatorhub.  Can we get a new release cut here please?

https://github.com/prometheus-operator/prometheus-operator/releases

**Comment by camilamacedo86** [comment]
Hi @paulczar,

You need to reach out its Operator author and ask to them create new bundle versions and push PRs to this repo. We can't do that for them.  Could you please raise this request in the project repo?

In this way, I am closing this one.

**Comment by simonpasquier** [comment]
Prometheus operator upstream maintainer here :) 
Unfortunately the prometheus operator's team has never been involved in maintaining the bundle.
