### ISSUE TITLE
Update the readme to clarifies where and how this repo is used

### ISSUE THREAD

**Issue by camilamacedo86** [k8s-operatorhub/community-operators#737]
We need to add into the readme:
- That the image built from the projects merged here is quay.io/operatorhubio/catalog:latest
- Clarifies that this repository is used to create the website and the image
- Clarifies that the solutions merged here ought to work in the k8s cluster but also terically can be used in its vendor
- That the image built is not used in OCP or OKD and add the link for https://github.com/redhat-openshift-ecosystem/community-operators-prod to let the users know where they should push their solutions if they are looking for distributed their solutions by default in these vendors
- Also, we need to add the steps over how to consume this source in OLM ( k8s cluster via command line ) and in OCP/OKD via console/UI.

**Comment by J0zi** [comment]
for now, it is here https://k8s-operatorhub.github.io/community-operators/operator-release-process/#operator-is-published

**Comment by camilamacedo86** [comment]
Hi @J0zi, 

IMO we need to make it clear on the README. See, for i.e:  https://github.com/k8s-operatorhub/community-operators/discussions/1044

**Comment by camilamacedo86** [comment]
We actually update the readme on this one. The only missing point was added with https://github.com/k8s-operatorhub/community-operators/pull/1217
