### ISSUE TITLE
Bump SDK and replace ansible check 

### ISSUE THREAD

**Issue by camilamacedo86** [k8s-operatorhub/community-operators#738]
See the following error.
https://github.com/k8s-operatorhub/community-operators/runs/5113897313?check_suite_focus=true#step:6:718

We should bump SDK [1.17.0](https://github.com/operator-framework/operator-sdk/releases/tag/v1.17.0) and remove this ansible playbook check now that the test is done by SDK. See: https://github.com/operator-framework/operator-sdk/pull/5495

**Comment by camilamacedo86** [comment]
c/c @richardw @mvalarh @J0zi

**Comment by mvalarh** [comment]
This is already in production

**Comment by mvalarh** [comment]
https://github.com/k8s-operatorhub/community-operators/runs/5124955659?check_suite_focus=true

**Comment by mvalarh** [comment]
Version used is listed here: https://github.com/k8s-operatorhub/community-operators/runs/5124955659?check_suite_focus=true#step:6:156
