### ISSUE TITLE
CI pipeline prevents Minor Cosmetic Changes

### ISSUE THREAD

**Issue by wallrj** [k8s-operatorhub/community-operators#749]
In https://github.com/k8s-operatorhub/community-operators/issues/722 I expected label changes to be accepted as [Minor Cosmetic Changes](https://github.com/operator-framework/community-operators/blob/master/docs/operator-version-update.md#minor-cosmetics-changes)

![image](https://user-images.githubusercontent.com/978965/153618214-cc67565d-e437-4853-9996-64fde30b00aa.png)

I realise that that document doesn't include label changes in this category, but I put that down to incomplete documentation.
The reason I thought that, is that an identical PR was submitted by @yselkowitz in https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/434 and merged after passing all the CI checks.

And I can see that this PR has been labelled `allow/operator-recreate`. 

Have I understood correctly?

What do you think?

_Originally posted by @wallrj in https://github.com/k8s-operatorhub/community-operators/issues/722#issuecomment-1036331955_

**Comment by wallrj** [comment]
Here are links and extracts from the documentation that I am referring to:

## [Updating your existing Operator](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-operator.md#updating-your-existing-operator)
> Unless of purely cosmetic nature, subsequent updates to your Operator should result in new bundle directories being added, containing an updated CSV as well as copied, updated and/or potentially newly added CRDs. Within your new CSV, update the spec.version field to the desired new semantic version of your Operator.

## [Operator deploy tests (lemon/orange) test failures](https://k8s-operatorhub.github.io/community-operators/troubleshooting/#operator-deploy-tests-lemonoragne-test-failures)
> All operator versions are already in catalog
> You are trying to edit an existing operator version. It is not recommended. But there are some exceptions, where you just edit some description or link. In this case, repository maintainers can set appropriate labels to override such errors and approve release pipeline action to overwrite an existing operator.

## [Minor (cosmetics) changes](https://github.com/operator-framework/community-operators/blob/master/docs/operator-version-update.md#minor-cosmetics-changes)
> There are some case when only some minor changes to the existing operator are needed (like description update or an update of icon). In this case pipeline will set corresponding label and automatically handle such case.

**Comment by wallrj** [comment]
And I suppose the reason for not allowing e.g. ServiceAccount changes to existing bundles is that OLM would have no way to upgrade users who had already installed the existing bundle.
Here for example. The cert-manager 1.6.1 bundle will already be wide spread use. So if I change the ServiceAccount for 1.6.1 and if the CI allowed that, and if those updated packages got published to the OLM catalogue then we'd end up with users with slightly different OLM installations of cert-manager 1.6.1, which will cause confusion at best and may cause upgrade headaches at worst.

**Comment by J0zi** [comment]
@wallrj in case single version change, we are checking if change is cosmetic
In case of multiple versions change, we are creating new bundles again, but old bundles are still present and valid for previous versions of catalog.
Service account issue is just output from the newest `operator-sdk`. It wasn't there in older version. @camilamacedo86 already explained in https://github.com/k8s-operatorhub/community-operators/pull/722#issuecomment-1036331955

**Comment by camilamacedo86** [comment]
HI @wallrj, 

You must solve the SA issue. Allow this configuration in the bundle was a bug since OLM will be unable to handle it. 
So, I'd recommend you check all bundles against the latest SDK version 1.17.0 and the command `operator-sdk bundle validate <bundle-path> --select-optional suite=operatorframework` and fix the previous ones as well if that is the case. Please, create a PR for each bundle version if you need to do that. 

c/c @mvalarh @J0zi
