### ISSUE TITLE
Document how to deprecate an operator

### ISSUE THREAD

**Issue by wallrj** [k8s-operatorhub/community-operators#750]
In https://github.com/k8s-operatorhub/community-operators/pull/529 the hazelcast-operator has been deprecated by adding a `[DEPRECATED] ` prefix to its name, but is this the recommended process?

On operatorhub.io, this has the effect of showing the deprecated operators *first*:
 * https://github.com/k8s-operatorhub/community-operators/issues/549
 * https://github.com/k8s-operatorhub/operatorhub.io/issues/13

Some of the documentation mentions a `maturity: deprecated` field / value pair, but does not elaborate further:
 * https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-metadata
 * https://docs.okd.io/4.9/operators/operator_sdk/osdk-generating-csvs.html#osdk-manually-defined-csv-fields_osdk-generating-csvs

(It is confusing that the word "maturity" is used elsewhere in reference to `metadata.capabilities` and   [Operator Capabilities](https://operatorframework.io/operator-capabilities/))

I'd like some documentation recommending when and how to deprecate an operator.

**Comment by camilamacedo86** [comment]
@wallrj, 

That is something that requires discussion, alignments and some effort. 
But we will try to check it out and keep you updated. See my comment: https://github.com/k8s-operatorhub/community-operators/issues/549#issuecomment-1036539967

**Comment by camilamacedo86** [comment]
The option to add a feature to address this requirement has been discussed into the EP: https://github.com/operator-framework/enhancements/pull/113/files
