### ISSUE TITLE
Error in Operator Release workflow: operator was not published on operatorhub.io after it merged

### ISSUE THREAD

**Issue by wallrj** [k8s-operatorhub/community-operators#783]
I merged 
 * https://github.com/k8s-operatorhub/community-operators/pull/780 

but it didn't get published to operatorhub.io

The [Operator Release workflow](https://github.com/k8s-operatorhub/community-operators/blob/50e434048ca5a1badf32772f92b3a7bbe17e6b04/.github/workflows/operator_release.yaml) [failed](https://github.com/k8s-operatorhub/community-operators/actions/runs/1855354765) 

> 
> TASK [operator_index : Add 'couchbase-enterprise' operator to index image quay.io/operatorhubio/catalog_tmp:latest] ***
> ...
> time="2022-02-16T22:14:37Z" level=error msg="permissive mode disabled" bundles="[quay.io/operatorhubio/couchbase-enterprise:v1.0.0 quay.io/operatorhubio/couchbase-enterprise:v1.1.0 quay.io/operatorhubio/couchbase-enterprise:v1.2.1 quay.io/operatorhubio/couchbase-enterprise:v1.2.2 quay.io/operatorhubio/couchbase-enterprise:v2.0.0 quay.io/operatorhubio/couchbase-enterprise:v2.0.1 quay.io/operatorhubio/couchbase-enterprise:v2.0.2 quay.io/operatorhubio/couchbase-enterprise:v2.1.0]" error="add prunes bundle couchbase-operator.v1.0.0 (quay.io/operatorhubio/couchbase-enterprise:v1.0.0) from package couchbase-enterprise, channel stable: this may be due to incorrect channel head (couchbase-operator.v2.1.0, skips/replaces [couchbase-operator.v2.0.2])"
>     Error: add prunes bundle couchbase-operator.v1.0.0 (quay.io/operatorhubio/couchbase-enterprise:v1.0.0) from package couchbase-enterprise, channel stable: this may be due to incorrect channel head (couchbase-operator.v2.1.0, skips/replaces [couchbase-operator.v2.0.2])
> 

https://github.com/k8s-operatorhub/community-operators/runs/5223824016?check_suite_focus=true

**Comment by wallrj** [comment]
Ah, perhaps this will be fixed by:
 * https://github.com/k8s-operatorhub/community-operators/pull/782
 * https://github.com/k8s-operatorhub/community-operators/pull/782/commits/cd21785a194c10da52875f34b465659af55cb58a

But that begs the questions:

1. How come [the previous operator got successfully deployed](https://github.com/k8s-operatorhub/community-operators/commit/2af4d4afd93e5378610e2c6cb518c8b7923163db), only a few hours earlier, and [other recent commits to master were also successfully deployed](https://github.com/k8s-operatorhub/community-operators/commits/main).
2. How come the pre-submit checks didn't prevent merging CSV with the missing "replaces" field during [previous changes to the Couchbase CSV file](https://github.com/k8s-operatorhub/community-operators/commits/cd21785a194c10da52875f34b465659af55cb58a/operators/couchbase-enterprise/1.1.0/manifests/couchbase-v1.1.0.clusterserviceversion.yaml).

**Comment by mvalarh** [comment]
@wallrj yes. it will be fixed in https://github.com/k8s-operatorhub/community-operators/actions/runs/1858645246

**Comment by mvalarh** [comment]
Fixed
